config/routes.rb
QA::Application.routes.draw do
  get "admin/dashboard"
  devise_for :users
  resources :categories, only: [:show] do
    resources :questions, except: [:index] do
      get 'fix'
      resources :answers, except: [:index, :show ] do
        get 'like'
        get 'unlike'
      end
    end
  end
  resources :users, only: [:show]

  root :to => "home#index"

  namespace :admin do
    resources :users, except: [:new, :create, :show]
    resources :categories do
      member do
        get 'addchild'
        post 'addchild'
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_ancestry
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :addchild]
  layout 'admin'

  # GET /categories
  # GET /categories.json
  def index
    @pucrs = Category.where("name = '#{QA::Application.config.main_category}'").first
    if @pucrs == nil
      @pucrs = Category.create!(name: "#{QA::Application.config.main_category}", description: "Pontifícia Universidade Católica do Rio Grande do Sul")
    end    
    redirect_to admin_category_path(@pucrs)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category.parent.nil? ? @category : @category.parent), notice: 'A categoria foi criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: 'A categoria foi atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @parent = @category.parent
    @category.destroy
    respond_to do |format|
      if @parent.nil?
        format.html { redirect_to admin_categories_path }
        format.json { head :no_content }
      else
        format.html { redirect_to admin_category_path(@parent), notice: 'A categoria foi removida com sucesso.' }
        format.json { render action: 'show', location: @parent }        
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :parent_id, :id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_cat.html.erb
    <tr>
        <td>
        <%
          strAncestors = ""
          if category.ancestors.any?
            
            category.ancestors.each do |category|
              strAncestors += category.name + " / "
            end
          end
          if strAncestors != "" %>
            <span data-tooltip class="has-tip" title="<%= strAncestors[0...-3] %>"><%= category.name %></span>
          <% else
            concat category.name
          end
        %>
        </td>
        <td><%= category.description %></td>
        <td><%= link_to content_tag("i", '', class: "fi-magnifying-glass"), admin_category_path(category), class: 'icon', title: 'Visualizar' %></td>
        <td><%= link_to content_tag("i", '', class: "fi-plus"), addchild_admin_category_path(category), class: 'icon', title: 'Adicionar Subcategoria' %></td>
        <% if category.name != "#{QA::Application.config.main_category}" %>
        <td><%= link_to content_tag('i', '', class: 'fi-page-edit'), edit_admin_category_path(category), class: 'icon', title: 'Editar Categoria' %></td>
        <td><%= link_to content_tag("i", '', class: "fi-trash"), admin_category_path(category), method: :delete, class: 'icon', title: 'Apagar Categoria' %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category], html: { class: "custom" }) do |f| %>
  <% eh_pucrs = @category.name == "#{QA::Application.config.main_category}" %>
  <div class="row">
    <div class="large-6 columns" role="content">
      <%= f.label :name, "Categoria" %><br>
      <%= f.text_field :name, autocomplete: true, autofocus: !eh_pucrs, disabled: eh_pucrs %>
    </div>
    <div class="large-6 columns">
      <%= f.label :parent_id, "Categoria Pai" %><br>
      <%= f.collection_select :parent_id, Category.order(:name).where(@category.id != nil ? "id != #{@category.id}" : ""), :id, :name, include_blank: false, class: "small" %>
    </div>
  </div>

  <div class="row">  
    <div class="large-12 columns">
      <%= f.label :description, "Descrição" %><br>
      <%= f.text_area :description, autocomplete: true, disabled: eh_pucrs %>
    </div>
  </div>
  
  <div class="row">
    <div class="large-12 columns">
      <% btnLbl = controller.action_name == "new" ? "Inserir" : "Atualizar" %>
      <%= f.submit btnLbl, class: "small button", disabled: eh_pucrs %>
    </div>
  </div>
<% end %>

app/views/admin/categories/addchild.html.erb
<%
  @filho = Category.new
%>
<%- title "Admin - Adicionar Filho: #{@category.name}" %>
<div class="large-12 columns" role="content">
  <h3>Adicionar Filho: <%= @category.name %></h3>
  <%= form_for([:admin, @filho], url: admin_categories_path, html: { class: "custom" }) do |f| %>
    <div class="row">
      <div class="large-6 columns" role="content">
        <%= f.label :name, "Categoria" %><br>
        <%= f.text_field :name, autocomplete: true, autofocus: true %>
        <%= f.hidden_field :parent_id, value: @category.id %>
      </div>
    </div>

    <div class="row">  
      <div class="large-12 columns">
        <%= f.label :description, "Descrição" %><br>
        <%= f.text_area :description, autocomplete: true %>
      </div>
    </div>
    
    <div class="row">
      <div class="large-12 columns">
        <%= f.submit "Adicionar", class: "small button" %>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/categories/edit.html.erb
<%- title "Admin - Editar Categoria: #{@category.name}" %>
<div class="large-12 columns" role="content">
  <h3>Editar Categoria</h3>
  <%= render 'form' %>
</div>

app/views/admin/categories/index.html.erb
{
  "endVersion": "A-2493,B-2224,C-97",
  "items": [
    {
      "enabled": true,
      "entityId": "891B19FB-DC84-B4BD-AF9B-3F19323B1ECD",
      "entityType": "payee",
      "autoFillAmount": -44.22,
      "autoFillCategoryId": "A19",
      "autoFillMemo": "",
      "isTombstone": false,
      "entityVersion": "A-2492",
      "madeWithKnowledge": null,
      "isResolvedConflict": false,
      "targetAccountId": null,
      "name": "Bife"
    },
    {
      "YNABID": null,
      "entityId": "20952DCA-CE88-90E0-0AAF-3F1906AA3C1E",
      "accepted": true,
      "entityType": "transaction",
      "FITID": null,
      "date": "2013-05-30",
      "isTombstone": false,
      "amount": -44.22,
      "madeWi

app/views/admin/categories/new.html.erb
<%- title "Admin - Nova Categoria" %>
<div class="large-12 columns" role="content">
  <h3>Nova Categoria</h3>
  <%= render 'form' %>
</div>

app/views/admin/categories/show.html.erb
<%- title "Admin - Categoria: #{@category.name}" %>
<ul class="breadcrumbs">
<% @category.ancestors.each do |category| %>
  <li><%= link_to category.name, admin_category_path(category) %></li>
<% end %>
  <li class="current"><%= @category.name %></li>
</ul>

<h3><%= @category.name %>
  <%= link_to content_tag('i', '', class: 'fi-page-edit'), edit_admin_category_path(@category), class: 'icon', title: 'Editar Categoria' %>
  <%= link_to content_tag('i', '', class: 'fi-plus'), addchild_admin_category_path(@category), class: 'icon', title: 'Adicionar Subcategoria' %>
  <%= link_to content_tag('i', '', class: 'fi-trash'), admin_category_path(@category), method: :delete, class: 'icon', title: 'Apagar Categoria' %>
</h3>
<p><%= @category.description %></p>

<table>
  <thead>
    <tr>
      <th width="20%">Nome</th>
      <th width="50%">Descrição</th>
      <th width="5%"></th>
      <th width="5%"></th>
      <th width="5%"></th>
      <th width="5%"></th>
    </tr>
  </thead>
  <tbody>
    <% @category.children.each do |category| %>
      <%= render 'cat', category: category %>
    <% end %>    
  </tbody>
</table>