config/routes.rb
QA::Application.routes.draw do
  get "admin/dashboard"
  devise_for :users
  resources :categories, only: [:show] do
    resources :questions, except: [:index] do
      get 'fix'
      resources :answers, except: [:index, :show ] do
        get 'like'
        get 'unlike'
      end
    end
  end
  resources :users, only: [:show]

  root :to => "home#index"

  namespace :admin do
    resources :users, except: [:new, :create, :show]
    resources :categories do
      member do
        get 'addchild'
        post 'addchild'
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_ancestry
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :addchild]
  layout 'admin'

  # GET /categories
  # GET /categories.json
  def index
    @pucrs = Category.where("name = '#{QA::Application.config.main_category}'").first
    if @pucrs == nil
      @pucrs = Category.create!(name: "#{QA::Application.config.main_category}", description: "Pontifícia Universidade Católica do Rio Grande do Sul")
    end    
    redirect_to admin_category_path(@pucrs)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category.parent.nil? ? @category : @category.parent), notice: 'A categoria foi criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: 'A categoria foi atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @parent = @category.parent
    @category.destroy
    respond_to do |format|
      if @parent.nil?
        format.html { redirect_to admin_categories_path }
        format.json { head :no_content }
      else
        format.html { redirect_to admin_category_path(@parent), notice: 'A categoria foi removida com sucesso.' }
        format.json { render action: 'show', location: @parent }        
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :parent_id, :id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_answer.html.erb
<%
def getlikes(a)
  ret = ""
  Like.where("answer_id = #{a.id}").each do |like|
    u = User.find(like.user_id)
    
    ret += (ret == "" ? "" : ", ") + u.first_name + " " + u.last_name
  end
  ret
end
def monta_likes(a)
  if a.likes > 0
    raw("<span data-tooltip class=\"has-tip\" title=\"" + getlikes(a) + "\">" + a.likes.to_s + (a.likes > 1 ? " gostaram." : " gostou.") + "</span>")
  else
    ""
  end
end
%>
<% @user = answer.user_id.nil? ? nil : User.find(answer.user_id) %>
      <div class="indented comment push">
        <section class="top">
          <h6 class="byline">
            <% if !@user.nil? %>
              <%= link_to raw("<i class=\"usericon\"></i> " + @user.first_name), @user -%>
            <%else%>
              <i class="usericon"></i>Usuário Desconhecido
            <%end%>
            <small>em 
              <span class="data">
                <%= answer.created_at.strftime("%d/%m/%Y %H:%M:%S") %>
              </span>
            </small>
          </h6>
        </section>
        <section class="content">
          <p class="justify"><%= answer.description %></p> 
        </section>
        <section class="actions">
          <ul class="inline-list">
            <li><%= monta_likes(answer) %></li>
        <% if user_signed_in?
          question = Question.find(answer.question_id) %>            
            <% likes = Like.where("user_id = #{current_user.id} and question_id = #{question.id} and answer_id = #{answer.id}").first
              if likes.nil? %>
            <li><%= link_to "Gostei", category_question_answer_like_path(question.category_id, question.id, answer.id) %></li>
            <% else %>
            <li><%= link_to "Gostei (desfazer)", category_question_answer_unlike_path(question.category_id, question.id, answer.id) %></li>
            <% end %>
            <%
              if current_user.id == answer.user_id || current_user.user_level > 0 %>
              <li><%= link_to "Editar", edit_category_question_answer_path(question.category_id, answer.question_id, answer) %></li>
              <li><%= link_to 'Apagar', category_question_answer_path(question.category_id, answer.question_id, answer), method: :delete, data: { confirm: 'Tem certeza?' } %></li><%
              end
            %>
            <% end %>
          </ul>
        </section>
        
      </div>

app/views/categories/_breadcrumb.html.erb
<ul class="breadcrumbs">
  <li><%= link_to "Home", "/" %></li>
<% category.ancestors.each do |subcat| %>
  <li><%= link_to subcat.name, subcat %></li>
<% end %>
  <li><%= link_to category.name, category %></li>
</ul>

app/views/categories/_miniquestion.html.erb
<%
  def foirespondida(q)
    c = Answer.where("question_id = #{q.id}").count
    if c <= 0
      " (sem respostas)"
    elsif c == 1
      " (#{c} resposta)"
    else
      " (#{c} respostas)"      
    end
  end
%>
<% @user = question.user_id.nil? ? nil : User.find(question.user_id) %>
<article>
  <div class="row">
    <div class="large-8  small-8 columns">
    <h4><% if question.fixed %>
      <%= raw(content_tag('i', '', class: 'icon fi-star')) %>
    <% end %>
      <%= link_to question.title, category_question_path(question.category_id, question) %></h4><span><%= foirespondida(question) %></span>
    </div>
    <div class="large-4 small-4 columns">
      <div class="comment">
        <section class="top">
          <h6 class="byline">
            <% if !@user.nil? %>
              <%= link_to raw("<i class=\"usericon\"></i> " + @user.first_name), @user -%>
            <%else%>
              <i class="usericon"></i>Usuário Desconhecido
            <%end%>
            <small>em 
              <span class="data">
                <%= question.created_at.strftime("%d/%m/%Y %H:%M:%S") %>
              </span>
            </small>
          </h6>
        </section>
      </div>
    </div>
  </div>
</article>
<hr />

app/views/categories/_question.html.erb
<% @user = question.user_id.nil? ? nil : User.find(question.user_id) %>
<article>
  <div class="row">
    <div class="large-12  small-12 columns">
      <h3><% if question.fixed %>
      <%= raw(content_tag('i', '', class: 'icon fi-star')) %>
    <% end %><%= link_to question.title, category_question_path(question.category_id, question) %></h3>
      <div class="comment">
        <section class="top">
          <h6 class="byline">
            <% if !@user.nil? %>
              <%= link_to raw("<i class=\"usericon\"></i> " + @user.first_name), @user -%>
            <%else%>
              <i class="usericon"></i>Usuário Desconhecido
            <%end%>
            <small>em 
              <span class="data">
                <%= question.created_at.strftime("%d/%m/%Y %H:%M:%S") %>
              </span>
            </small>
          </h6>
        </section>
        <section class="content">
          <p class="justify"><%= question.description %></p> 
        </section>
        <% if user_signed_in? %>
        <section class="actions">
          <ul class="inline-list">
            <li><%= link_to "Responder", new_category_question_answer_path(question.category_id, question) %></li>
            <%
              if current_user.id == question.user_id || current_user.user_level > 0 %>
              <li><%= link_to "Editar", edit_category_question_path(question.category_id, question) %></li>
              <li><%= link_to 'Apagar', category_question_path(question.category_id, question), method: :delete, data: { confirm: 'Tem certeza?' } %></li><%
                if current_user.user_level > 0
                  lbl = question.fixed ? "Desafixar" : "Fixar"%>
                  <li><%= link_to lbl, category_question_fix_path(question.category_id, question) %></li>
                <% end

              end
            %>
          </ul>
        </section>
        <% end %>
      </div>
      <h4>Respostas</h4>
      <% Answer.where("question_id = #{question.id}").order("likes DESC").each do |ans| %>
        <%= render '/categories/answer', answer: ans %>
      <% end %>
    </div>
  </div>
</article>
<hr />

app/views/categories/show.html.erb
<%- title "Categorias" %>
<%= render 'categories/breadcrumb', category: @category %>
<h4><%= @category.description %></h4>
<%= link_to 'Nova Pergunta', new_category_question_path(@category), class: "small button" %>
<hr />
<%
  strWhere = "category_id = #{@category.id}"
  search = params[:search]
  order = params[:order]
  onlyUnanswered = params[:un] == "true"
  ord = "(case when fixed then 1 else 2 end) ASC, created_at"

  if !order.nil?
    if order == "ASC"
      ord += " ASC"
    else
      ord += " DESC"
    end
  end

  if !search.nil? && !search.empty?
    strWhere += " and (title ilike '%#{search}%' or description ilike '%#{search}%')"
  end
  %>
  <div class="large-12 columns">
    <ul class="inline-list right">
      <li>Filtros</li>
      <li> <%= link_to raw(onlyUnanswered ? "Perguntas: Todas" : "Perguntas: Somente não respondidas"), request.parameters.merge(un: !onlyUnanswered, order: order) %></li>
      <li><%= link_to raw(order == "ASC" ? "Ordem: Novas primeiro" : "Ordem: Antigas primeiro"), request.parameters.merge(un: onlyUnanswered, order: order == "ASC" ? "DESC" : "ASC") %></li>      
    </ul>
  </div>
  <%
  Question.where(strWhere).order(ord).each do |que|
  next if onlyUnanswered && Answer.where("question_id = #{que.id}").size > 0 %>
  <%= render 'miniquestion', question: que %>
<% end %>