config/routes.rb
QA::Application.routes.draw do
  get "admin/dashboard"
  devise_for :users
  resources :categories, only: [:show] do
    resources :questions, except: [:index] do
      get 'fix'
      resources :answers, except: [:index, :show ] do
        get 'like'
        get 'unlike'
      end
    end
  end
  resources :users, only: [:show]

  root :to => "home#index"

  namespace :admin do
    resources :users, except: [:new, :create, :show]
    resources :categories do
      member do
        get 'addchild'
        post 'addchild'
      end
    end
  end
end

app/views/layouts/_adminsidebar.html.erb
      <!-- Sidebar -->
   
      <aside class="large-3 columns">
        <h5>Opções</h5>
        <ul class="side-nav">
          <li><%= link_to "Categorias", admin_categories_path %></li>
          <li><%= link_to "Usuários", admin_users_path %></li>
        </ul>
      </aside>
   
      <!-- End Sidebar -->

app/views/layouts/_catmenu.html.erb
<%
  def menu(category)
    c = category.has_children? ? "has-dropdown" : "" %>
    <%= content_tag :li, class: c do %><%= link_to category.name, category %>
      <% if category.has_children? %>
        <%= content_tag :ul, class: "dropdown" do %>
        <% category.children.order("name ASC").each { |c| menu(c) }
        end
      end
    end
  end


  @pucrs = Category.where("name = '#{QA::Application.config.main_category}'").first

  menu(@pucrs) if !@pucrs.nil?
%>

app/views/layouts/_links.html.erb
  <li><%= link_to raw(content_tag('i', '', class: 'icon fi-home') << ' Home'), "/", class: className %></li>
<% if user_signed_in? %>
  <li><%= link_to raw(content_tag('i', '', class: 'icon fi-torso') << ' Editar Perfil'), edit_user_registration_path, class: className %></li>
  <% if current_user.user_level > 0 %>
    <li>
      <%= link_to raw(content_tag('i', '', class: 'icon fi-wrench') << ' Painel'), admin_dashboard_path, class: className %></li>
  <% end %>
  <li><%= link_to raw(content_tag('i', '', class: 'icon fi-power') << ' Sair'), destroy_user_session_path, method: :delete, class: className %></li>
<% else %>
  <li><%= link_to raw(content_tag('i', '', class: 'icon fi-torso') << ' Entrar'), new_user_session_path, class: className %></li>
  <li><%= link_to raw(content_tag('i', '', class: 'icon fi-torsos-all') << ' Criar Conta'), new_user_registration_path, class: className %></li>
<% end %>

app/views/layouts/_usersidebar.html.erb
      <!-- Sidebar -->
   
      <aside class="large-3 columns">
        <div class="panel">
          <h5>Unidades Acadêmicas</h5>
          <ul class="side-nav">
            <li class="divider"></li>
            <%
              @pucrs = Category.where("name = '#{QA::Application.config.main_category}'").first
              if @pucrs != nil
                @pucrs.children.order("name ASC").each do |category| %>
                  <li><%= link_to category.name, category %></li>
                  <li class="divider"></li>
            <% end
            end %>
          </ul>
        </div>
   
      </aside>
   
      <!-- End Sidebar -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="pt"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="pt"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="pt"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="pt"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  	<title><%= content_for?(:title) ? QA::Application.config.main_title + " - " + content_for(:title) : QA::Application.config.main_title %></title>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Nav Bar -->
    <div class="row">
      <div class="large-12 columns">
        <div class="nav-bar right">
         <ul class="button-group">
            <%= render "layouts/links", className: "button" %>
          </ul>
        </div>
        <h1><%= link_to QA::Application.config.main_title, "/" %> <small><% if user_signed_in? %>Olá, <%= current_user.first_name %>!<% end %></small></h1>
        <hr />
      </div>
    </div>
   
    <!-- End Nav -->
    <!-- Main Page Content and Sidebar -->
   
    <div class="row">
   
      <!-- Main Blog Content -->
      <div class="large-9 columns" role="content">
        <% if !flash.empty? %>
          <div class="panel callout">
          <% flash.each do |name, msg| %>
            <%= content_tag :h5, msg, id: "flash_#{name}" %>
          <% end %>
          </div>
        <% end %>
        <%= yield %>
      </div>
   
      <!-- End Main Content -->
   
      <%= render 'layouts/adminsidebar' %>
      
    </div>
   
    <!-- End Main Content and Sidebar -->
    
    <!-- Footer -->
   
    <footer class="row">
      <div class="large-12 columns">
        <hr />
        <div class="row">
          <div class="large-6 columns">
            <p>&copy; GMPT Sistemas Ltda.</p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <%= render "layouts/links", className: "" %>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="pt"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="pt"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="pt"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="pt"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  	<title><%= content_for?(:title) ? QA::Application.config.main_title + " - " + content_for(:title) : QA::Application.config.main_title %></title>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Nav Bar -->
    <div class="row">
      <div class="large-12 columns">
        <div class="nav-bar right">
         <ul class="button-group">
            <%= render "layouts/links", className: "button" %>
          </ul>
        </div>
        <h1><%= link_to QA::Application.config.main_title, "/" %> <small><% if user_signed_in? %>Olá, <%= current_user.first_name %>!<% end %></small></h1>
        <hr />
        <div class="top-bar">
          <ul class="title-area">
            <li class="name">
              <h1><%= link_to "Home", "/" %></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
          </ul>
          <section class="top-bar-section">
            <ul class="left">
              <li class="divider hide-for-small"></li>
              <%= render 'layouts/catmenu' %>
            </ul>
            <ul class="right">
              <li class="has-form">
                <form method="get">
                  <div class="row collapse">
                    <div class="small-8 columns">
                      <input type="text" name="search" value="<%= params[:search] %>" />
                    </div>
                    <div class="small-4 columns">
                      <input class="button" type="submit" value="Pesquisar" />
                    </div>
                  </div>
                </form>
              </li>              
            </ul>
          </section>
        </div>
      </div>
    </div>
   
    <!-- End Nav -->
    <!-- Main Page Content and Sidebar -->
   
    <div class="row">
   
      <!-- Main Blog Content -->
      <div class="large-9 columns" role="content">
        <% if !flash.empty? %>
          <div class="panel callout">
          <% flash.each do |name, msg| %>
            <%= content_tag :h5, msg, id: "flash_#{name}" %>
          <% end %>
          </div>
        <% end %>
        <%= yield %>
      </div>
   
      <!-- End Main Content -->
   
      <%= render 'layouts/usersidebar' %>
      
    </div>
   
    <!-- End Main Content and Sidebar -->
    
    <!-- Footer -->
   
    <footer class="row">
      <div class="large-12 columns">
        <hr />
        <div class="row">
          <div class="large-6 columns">
            <p>&copy; GMPT Sistemas Ltda.</p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <%= render "layouts/links", className: "" %>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- If you delete this meta tag, Half Life 3 will never be released. -->
<meta name="viewport" content="width=device-width" />

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Q&A PUCRS</title>

</head>
 
<body bgcolor="#FFFFFF">
<!-- HEADER -->
<table class="head-wrap" bgcolor="#BFBFBF">
  <tr>
    <td></td>
    <td class="header container" >
        <div class="content">
        <table bgcolor="#BFBFBF">
          <tr>
            <td><h3>Q&A PUCRS</h3></td>
            <td align="right"><h6 class="collapse">Contato</h6></td>
          </tr>
        </table>
        </div>
    </td>
    <td></td>
  </tr>
</table><!-- /HEADER -->

<!-- BODY -->
<table class="body-wrap">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <div class="content">
      <table>
        <tr>
          <td>
            <%= yield %>
          </td>
        </tr>
      </table>
      </div><!-- /content -->
                  
    </td>
    <td></td>
  </tr>
</table><!-- /BODY -->

</body>
</html>